### ISSUE TITLE
Cannot use ApplySyntax plugin

### ISSUE THREAD

**Issue by SystemDisc** [princemaple/ngx-html-syntax#1]
Your example shows `Angular2HTML/Angular2HTML` as the value for `syntax` for the ApplySyntax plugin but that file does not exist in packages after installing Angular​2 HTML Syntax.

The Angular​2 HTML Syntax plugin is working and I can manually switch to the syntax, but I would like it to switch automatically.

**Comment by princemaple** [comment]
Sorry about that, I've updated the README to reflect the real path.

My personal dev package is obviously not using the same name as the package that other users would have when installed through package control. My apologies.
