### ISSUE TITLE
Html syntax in TypeScript file

### ISSUE THREAD

**Issue by Laoujin** [princemaple/ngx-html-syntax#10]
```
@Component({
    template: `<span>testy</span>`
 })
```

Any chance to support the AngularX html syntax there aswell? :)

**Comment by princemaple** [comment]
No plan of doing that, since I always use external HTML. However, if you are interested, you could look into how they implement this in VS Code.

**Comment by princemaple** [comment]
Closing since this belongs to the typescript area.
