### ISSUE TITLE
Not showing up after install in Sublime 3 version 3.0

### ISSUE THREAD

**Issue by aaronj84** [princemaple/ngx-html-syntax#11]
Hey, i tried installing via Package Installer and by manually cloning in my Packages folder, but still can't see it as an available syntax. I'm on Mac OS X High Sierra, Sublime 3 version 3.0 Build 3143

**Comment by princemaple** [comment]
All Good? :)

**Comment by aaronj84** [comment]
Yeah, I noticed it appears as ngx, I had been expecting it to be called Angular2. Just an oversight on my part

**Comment by princemaple** [comment]
Right. I created this package when Angular was still 2. And then Angular
released 4 and announced how Angular related stuff should be named. I
partially updated this package to reflect that. Haven't got to rename the
package itself yet.
