### ISSUE TITLE
Not working on Build 3143?

### ISSUE THREAD

**Issue by eriktodx** [princemaple/ngx-html-syntax#12]
I just installed [this ](https://packagecontrol.io/packages/Angular2%20HTML%20Syntax) via [Package Control](https://packagecontrol.io/) and I can't find this syntax under `View` -> `Syntax`.

I also installed `ApplySyntax` and added the section mentioned in the [README.md](https://github.com/princemaple/angular2-html-syntax/blob/master/README.md) under `Preferences` -> `Package Settings` -> `ApplySyntax` -> `Settings` still nothing...

I did change the `extensions` property to `["html"]`, to apply it globally, no?

**Comment by princemaple** [comment]
The syntax is called Ngx HTML

**Comment by eriktodx** [comment]
Got it. Why not fix the README.md? This is very confusing.

**Comment by princemaple** [comment]
The readme is correct.

**Comment by princemaple** [comment]
I haven't got to rename it on package control.

**Comment by ghost** [comment]
Was also confused by this, as this site here also has it wrong: http://blog.netgloo.com/2017/03/09/setup-sublime-text-3-for-angular/

**Comment by princemaple** [comment]
Blog posts can be outdated pretty fast nowadays. Especially I have nothing to do with that post. I'm sorry about the inconvenience.

**Comment by princemaple** [comment]
https://github.com/wbond/package_control_channel/pull/6779
