### ISSUE TITLE
Problem with style attribute

### ISSUE THREAD

**Issue by Glaived** [princemaple/ngx-html-syntax#13]
Example with HTML synthax:

![1](https://user-images.githubusercontent.com/1835170/33665272-a96da7d2-da96-11e7-9f25-16edb38c3296.png)

Example with Ngx HTML synthax:

![2](https://user-images.githubusercontent.com/1835170/33665285-b3fccf16-da96-11e7-95a1-ba5e28238b51.png)

**Comment by princemaple** [comment]
Hi @Glaived , it's weird. It displays correct CSS syntax highlighting for me. Also, this syntax is a superset of the official HTML syntax. There should be no difference at all other than highlighting the Angular specific stuff correctly. Please check your color scheme and CSS package.

**Comment by princemaple** [comment]
Feel free to reopen if you still think it's this package's fault.

**Comment by Glaived** [comment]
My friend and me on two different PCs have the same problem, on a 3rd PC, I disabled all my plugin to try: same problem.

**Comment by princemaple** [comment]
![image](https://user-images.githubusercontent.com/1329716/33795946-054e985e-dd3f-11e7-95ee-13a7318d4191.png)
I don't know what else I can say. (yes I set it to Ngx syntax)

**Comment by Glaived** [comment]
What is your color scheme ?

**Comment by princemaple** [comment]
Ayu (mirage)
