### ISSUE TITLE
Logical AND operator (&&) is highlighted as illegal

### ISSUE THREAD

**Issue by the-catalin** [princemaple/ngx-html-syntax#14]
Do I miss something?

![screenshot_38](https://user-images.githubusercontent.com/7150927/33784792-ccccdd62-dc6a-11e7-9224-8955571b7f41.jpg)

I fixed it by commenting these lines in Angular2HTML.sublime-syntax
```
  # entities:
  #   - include: entities-common
  #   - match: '&'
  #     scope: invalid.illegal.bad-ampersand.html
```

**Comment by princemaple** [comment]
This is inherited from the official HTML syntax. I never use `&&` in template so never thought that it is a problem. I think I have a better solution, will play a bit and get back to you.

**Comment by princemaple** [comment]
Should be fixed by https://github.com/princemaple/ngx-html-syntax/commit/f42545b1290239d07e6ca6d4af95181e3a9ef74a

And now the js expressions in the angular bindings are highlighted as js. (taking advantage of sublime text build 3156+, from the dev channel)

**Comment by the-catalin** [comment]
Thanks for the fix!

Mind me asking, you said you never use `&&` in template, but how do you deal with AND logic in a template? I feel I miss something obvious here...

**Comment by princemaple** [comment]
Well, you always have the option to extract the logic into a method, and call the method in the template instead of writing out the whole logic.
