### ISSUE TITLE
Incorrect syntax highlighting

### ISSUE THREAD

**Issue by rvinzent** [princemaple/ngx-html-syntax#15]
Most of my expressions are now incorrectly highlighted since the update. Any `===` opertator only has the first `=` as white and all of the following HTML until the `"` _after_ the next `"` is now displayed as yellow.
Example screenshot:
![image](https://user-images.githubusercontent.com/34038882/33844114-2755e176-de54-11e7-9a02-209dbc1a4119.png)

I love this package and it's hard to write Angular HTML without it, so a prompt fix would be very much appreciated. Thanks!

**Comment by princemaple** [comment]
I'll look into it soon.

**Comment by princemaple** [comment]
I just typed up the whole piece in your screenshot:

![image](https://user-images.githubusercontent.com/1329716/33853438-105ecfd2-df12-11e7-88c8-93dc539a0dd8.png)

It does not appear to be a problem on my end.

Are you using a custom JS syntax definition? FYI, I use the official one.

**Comment by princemaple** [comment]
and with Consolas font. (the above is with FiraCode), just to show that it's not a font problem.

![image](https://user-images.githubusercontent.com/1329716/33853532-69caebb4-df12-11e7-8687-cab573f4eb9b.png)

**Comment by rvinzent** [comment]
I have only applied your package and TypeScript in my Sublime. 
Here is my `Angular2HTML.sublime-settings` file:
`{
	"extensions":
	[
		"component.html"
	],
	"tab_size": 2,
	"translate_tabs_to_spaces": true
}
`  

and here is my list of installed packages in case anything is incompatible:
`
	"installed_packages":
	[
		"Angular CLI",
		"Angular2 HTML Syntax",
		"ApplySyntax",
		"Package Control",
		"TypeScript",
		"TypeScript Syntax"
	]
`

Do you think that these would have anything to do with it? Everything else is default.

**Comment by princemaple** [comment]
They look fine. Could you send me the whole file? Feel free to change the variable names if they are confidential. Also, I'm going to need your ST version.

**Comment by princemaple** [comment]
Oh wait. I guess you are using the stable version? The latest syntax definition only works on the latest dev build. My [PR](https://github.com/wbond/package_control_channel/pull/6779) on package control, which prevents older builds from installing my latest version of the syntax, hasn't been merged yet, that's probably the reason that you are seeing the incorrect syntax highlighting.

**Comment by princemaple** [comment]
As a workaround for now, you can find an [older working version](https://github.com/princemaple/ngx-html-syntax/blob/4ca68eb5a52abe6c9fff0f65bc7ef60ad6ac6784/Angular2HTML.sublime-syntax) and overwrite yours in the Packages folder.

**Comment by rvinzent** [comment]
Thanks for your detective work! I'll probably just end up installing the latest dev build.

**Comment by princemaple** [comment]
> Thanks for your detective work! I'll probably just end up installing the latest dev build.

Yeah I'd recommend that as well. The dev builds are generally very stable, :)

**Comment by princemaple** [comment]
Closing it now, feel free to reopen if you see more problem. (or open a new one)

**Comment by FichteFoll** [comment]
FYI, `embed` has not reached a stable release yet.

**Comment by princemaple** [comment]
@FichteFoll thanks!

**Comment by Gilwe** [comment]
Hi @princemaple 
I have the same problem but I am not sure how do I switch to dev version.
I'm using ApplySyntax with:

```
"syntaxes": [
    {
        "syntax": "Ngx HTML/NgxHTML",
        "extensions": ["component.html"],
    }
```

Any help with installing the latest dev build as @rvinzent mentioned?

Thank you!
 
btw, I see no 'Ngx HTML' in the package control, if that says anything
