### ISSUE TITLE
'=' in HTML messes things up

### ISSUE THREAD

**Issue by Gilwe** [princemaple/ngx-html-syntax#16]
Hi, I have a problem regarding the highlighting in html:

![image](https://user-images.githubusercontent.com/21289132/34070933-9c315b6c-e276-11e7-9fc2-15017f31f9fd.png)

After the = in the fifth row, everything looks and acts like a string.

I have installed as written in the readme file:

In my ApplySyntax.sublime-settings
```
"syntaxes": [
    {
        "syntax": "Ngx HTML/NgxHTML",
        "extensions": ["component.html"],
    }
```

Also, I've installed using the ngx-html-syntax Package control.

This package is great, would appreciate help with this prob

Thanks!

**Comment by princemaple** [comment]
https://github.com/princemaple/ngx-html-syntax/issues/15 have you seen this?

**Comment by Gilwe** [comment]
Yes I have (deleted my comment there to open ths issue.
I just don't know how to use the dev build instead of the version I use right know

**Comment by princemaple** [comment]
Answering the questions one by one:

How to use dev build? go to sublimetext.com/3dev
Can we fix for stable version? No, the latest version of the package uses some dev features. The alternative is to grab an older version of the package.
Can't see Ngx in package control? I had sent a PR to rename the package from angular 2 HTML to the current name, while doing so I also marked as requiring sublime 3156+, which is higher than the current stable.

**Comment by princemaple** [comment]
Feel free to reopen or reply with more questions!

**Comment by Gilwe** [comment]
Ooooh
You mean the dev build of SublimeText itself.
I thought you ment  the dev ver of Ngx HTML in [this thread](https://github.com/princemaple/ngx-html-syntax/issues/15).

Thank you very much 👍

**Comment by princemaple** [comment]
Haha sorry about the miscommunication.
