### ISSUE TITLE
Can't locate on Package Control

### ISSUE THREAD

**Issue by DazDotOne** [princemaple/ngx-html-syntax#17]
Hey, Probably something simple but I can't seem to find this on package control.

What should it be showing up as?

I've Tried Ngx and Angular as keywords but it doesn't seem to show up.

Any Suggestions?

Many Thanks.

**Comment by princemaple** [comment]
https://github.com/princemaple/ngx-html-syntax/issues/16#issuecomment-352191658

Sorry about copy-pasting. I'm traveling and on my phone.

**Comment by DazDotOne** [comment]
Thanks for the quick reply. 

Shame I don't have a licence to use the dev builds but I look forward to being able to use this plugin in the future.

**Comment by pegamon** [comment]
Try this steps:
Via "Package control: Add Repository" add "https://github.com/princemaple/ngx-html-syntax.git"
then via "Package control: Install Package" add "ngx-html-syntax"

**Comment by DazDotOne** [comment]
Works like a charm @pegamon. Thanks a lot!

**Comment by princemaple** [comment]
@pegamon thanks for chiming in. @DazDotOne I assume you are on 3154? How does the syntax highlighting look on that?

BTW I'm going to leave the issue open, in case anyone has the same issue.

**Comment by pegamon** [comment]
With version 3154 highlighting of this version of ngx-html-syntax is not working quite right (there is problem with char '=' mentioned here:
https://github.com/princemaple/ngx-html-syntax/issues/16)
In my case, actual version of ngx-html-syntax is working with dev version 3156

**Comment by DazDotOne** [comment]
That's right 3154. I mean, the '=' caracter is the same colour as the quotes but that's not really a massive issue.

It's a lot better than no highlighting at all.

Thanks again for the help all.

**Comment by princemaple** [comment]
👍 great, thanks for the feedback guys.

**Comment by JohnM-729** [comment]
3.0 b3143 chiming in here with the same issue, @pegamon solution worked like a charm, and thanks @princemaple for the immensely useful plugin!

**Comment by princemaple** [comment]
@JohnM-729 pleasure!

**Comment by pravin-d** [comment]
+1

**Comment by jeffreylees** [comment]
@pegamon solution is not working for me now - anyone have any insight? I was hoping to include this plugin in an article I'm writing, but I can't properly install it to have a look and write about it :/ 

Can add the repo fine, but it still doesn't show up in the install packages menu, even after a restart of the program.

**Comment by sandrosimas** [comment]
@jeffreylees, It's a bug from Sublime Package Control dependency. You should follow this issue:
https://github.com/wbond/package_control/issues/1334
Follow the instruction of @marcotollini, it worked here. Don't forget to remove and add the repository again.
````
"downloader_precedence": {
    "linux": ["curl", "urllib", "wget"],
    "osx": ["curl", "urllib"],
    "windows": ["wininet"]
}
````
In preferences -> Package settings -> Package control -> Settings - User, so that you use curls as download manager that doesn't have problems with the new certificate settings.

**Comment by soundismore** [comment]
@sandro-csimas This solution worked for me. Running on mac.

**Comment by princemaple** [comment]
This package should have been installable directly from package control since last beta in May. Can anyone confirm that?
