### ISSUE TITLE
Highlighting breaks down with <style> blocks of CSS

### ISSUE THREAD

**Issue by MattTreichelYeah** [princemaple/ngx-html-syntax#19]
See title. Usually these sorts of blocks are brief, but prevents the highlighting from easily being used for all HTML files which would be nice.

![image](https://user-images.githubusercontent.com/6729569/38879791-321adf5c-4232-11e8-9ffa-f45f8a149110.png)

**Comment by MattTreichelYeah** [comment]
`<style type='text/css'></style>` works fine for some reason, but any content breaks it.

**Comment by princemaple** [comment]
![image](https://user-images.githubusercontent.com/1329716/39742977-09b4e50c-52d2-11e8-9000-7a41e6f31372.png)

Sorry I missed this. Doesn't seem to be a problem of my package though.
