### ISSUE TITLE
Does not support attributes with hyphens

### ISSUE THREAD

**Issue by SystemDisc** [princemaple/ngx-html-syntax#2]
The following does not receive syntax highlighting:
```html
<div [attr.data-toggle]="test"></div>
```

**Comment by princemaple** [comment]
https://github.com/princemaple/angular2-html-syntax/commit/817300623341a85ab5200ae0cfe5dc9afef65db9

**Comment by princemaple** [comment]
I've made the [release](https://github.com/princemaple/angular2-html-syntax/tree/v0.2.2), hopefully you will get it in a couple hours.

**Comment by SystemDisc** [comment]
Thanks! You're the best
