### ISSUE TITLE
Possibility to color differently function calls in html?

### ISSUE THREAD

**Issue by Nemesis19** [princemaple/ngx-html-syntax#20]
I'd like to know if it's possible to make the functions called in component.html of a more distinguishable way...a different color from vars.

Thanks

**Comment by princemaple** [comment]
Hi @Nemesis19 I don't think it's possible on my side. There is no magic in syntax highlighting JS code but simply defining the relevant chunk of the code as JS. The highlighting is done by your current JS syntax. You could try and use different JS syntax, or define your own :)
