### ISSUE TITLE
Not working for animation attributes

### ISSUE THREAD

**Issue by SystemDisc** [princemaple/ngx-html-syntax#3]
Sorry to bother you again, but syntax highlighting also misses the @ sign in front of animation attributes:

See `[@fadeAnimation]` below:

<img src="http://i.imgur.com/fhqDYqh.png">

**Comment by princemaple** [comment]
Hi, thanks for reporting!

I'm on phone.
Could you send a PR adding an "@" at https://github.com/princemaple/angular2-html-syntax/blob/master/Angular2HTML.sublime-syntax#L454 after "Z" or before "a"? Thanks!

**Comment by SystemDisc** [comment]
Shouldn't it be for `tag-ng-bind-attribute` at https://github.com/princemaple/angular2-html-syntax/blob/master/Angular2HTML.sublime-syntax#L440?

**Comment by princemaple** [comment]
You are right, I'm on phone and I'm blind :)

**Comment by SystemDisc** [comment]
Hopefully that does it :)

**Comment by princemaple** [comment]
Released, fingers crossed.

**Comment by princemaple** [comment]
Releasing on phone, new meta.
