### ISSUE TITLE
BracketHighLinter tag highlight not work

### ISSUE THREAD

**Issue by snowyYU** [princemaple/ngx-html-syntax#8]
hello .after i use this syntax the most work nice,but tag highlight not work,others,such as round,curly brace still work well
tks~

**Comment by princemaple** [comment]
Could you provide an example please?

**Comment by princemaple** [comment]
Hi @snowyYU tag highlighting has never been an issue, at least has never been brought up. I will need an example from you to debug. I haven't personally seen anything wrong with tags while I'm developing angular code. Also, the added syntax highlighting is only about attributes. All the tag highlighting comes from Sublime default html syntax.

**Comment by snowyYU** [comment]
![1](http://i.imgur.com/3iZj8ON.png)

before I change to ng2 syntax,the tag highlight

![](http://i.imgur.com/HvQvQBU.png)

and after,

thank you very much

**Comment by snowyYU** [comment]
just the tag highlight not work ,tks

**Comment by princemaple** [comment]
@snowyYU what was your original syntax?

**Comment by snowyYU** [comment]
the defualt html

**Comment by princemaple** [comment]
@snowyYU looks like what you need to do is to add "Angular2HTML" to this http://facelessuser.github.io/BracketHighlighter/customize/#tag_mode

I might change that to "Ngx HTML" too in the future, you might as well add both to be future proof.
