### ISSUE TITLE
*ngFor with index assignment

### ISSUE THREAD

**Issue by Laoujin** [princemaple/ngx-html-syntax#9]
Works perfectly

```
<div *ngFor="let itm of items" />
```

Breaks the highlighting:

```
<div *ngFor="let itm of items; let i=index" />
```

As soon as there is a `=` in the *ngFor, the rest of the template formatting is broken.

**Comment by princemaple** [comment]
![image](https://user-images.githubusercontent.com/1329716/30325089-bcd7e350-9806-11e7-834b-d7f4226beb9c.png)
Seems to work for me. Besides, we don't do anything inside the `"..."`, the inside part is just treated as a string, no magic at all. I don't know why it broke for you, maybe there are some other plugins that's doing the excessive work here.

**Comment by princemaple** [comment]
Irrelevant but have to ask, why do you have `/>` on a div tag? That doesn't make sense.

**Comment by Laoujin** [comment]
Oepsie... You are right, my mistake!

`<div />`: just an example I made up for the issue...
